on: 
  push:
  pull_request:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:  
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
           user_name: AlwaysMori
           text: Always Mori
      - name: Set Git User
        run: |
          git config user.name "AlwaysMori"
          git config user.email "nandaet16@gmail.com" 
      - uses: jasineri/simple-push-action@v1
